version: '3'

services:
  server:
    image: stefanocirici/laserbotbattle:server
    privileged: true
    network_mode: "host"
    expose:
      - "8000"
    volumes:
       - /var/run/dbus:/var/run/dbus
  
  robot:
    mage: stefanocirici/laserbotbattle:rosberry
    privileged: true
    network_mode: "host"
    expose:
      - "8000"
    volumes:
       - /var/run/dbus:/var/run/dbus
       - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static