// Generated by gencpp from file laser_bot_battle/AddNewRobot.msg
// DO NOT EDIT!


#ifndef LASER_BOT_BATTLE_MESSAGE_ADDNEWROBOT_H
#define LASER_BOT_BATTLE_MESSAGE_ADDNEWROBOT_H

#include <ros/service_traits.h>


#include <laser_bot_battle/AddNewRobotRequest.h>
#include <laser_bot_battle/AddNewRobotResponse.h>


namespace laser_bot_battle
{

struct AddNewRobot
{

typedef AddNewRobotRequest Request;
typedef AddNewRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddNewRobot
} // namespace laser_bot_battle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_bot_battle::AddNewRobot > {
  static const char* value()
  {
    return "0cb5143ed23a5de01874507c8711c4d5";
  }

  static const char* value(const ::laser_bot_battle::AddNewRobot&) { return value(); }
};

template<>
struct DataType< ::laser_bot_battle::AddNewRobot > {
  static const char* value()
  {
    return "laser_bot_battle/AddNewRobot";
  }

  static const char* value(const ::laser_bot_battle::AddNewRobot&) { return value(); }
};


// service_traits::MD5Sum< ::laser_bot_battle::AddNewRobotRequest> should match 
// service_traits::MD5Sum< ::laser_bot_battle::AddNewRobot > 
template<>
struct MD5Sum< ::laser_bot_battle::AddNewRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_bot_battle::AddNewRobot >::value();
  }
  static const char* value(const ::laser_bot_battle::AddNewRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_bot_battle::AddNewRobotRequest> should match 
// service_traits::DataType< ::laser_bot_battle::AddNewRobot > 
template<>
struct DataType< ::laser_bot_battle::AddNewRobotRequest>
{
  static const char* value()
  {
    return DataType< ::laser_bot_battle::AddNewRobot >::value();
  }
  static const char* value(const ::laser_bot_battle::AddNewRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_bot_battle::AddNewRobotResponse> should match 
// service_traits::MD5Sum< ::laser_bot_battle::AddNewRobot > 
template<>
struct MD5Sum< ::laser_bot_battle::AddNewRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_bot_battle::AddNewRobot >::value();
  }
  static const char* value(const ::laser_bot_battle::AddNewRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_bot_battle::AddNewRobotResponse> should match 
// service_traits::DataType< ::laser_bot_battle::AddNewRobot > 
template<>
struct DataType< ::laser_bot_battle::AddNewRobotResponse>
{
  static const char* value()
  {
    return DataType< ::laser_bot_battle::AddNewRobot >::value();
  }
  static const char* value(const ::laser_bot_battle::AddNewRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_BOT_BATTLE_MESSAGE_ADDNEWROBOT_H
