// Generated by gencpp from file laserbot_raspberry/AddNewRobot.msg
// DO NOT EDIT!


#ifndef LASERBOT_RASPBERRY_MESSAGE_ADDNEWROBOT_H
#define LASERBOT_RASPBERRY_MESSAGE_ADDNEWROBOT_H

#include <ros/service_traits.h>


#include <laserbot_raspberry/AddNewRobotRequest.h>
#include <laserbot_raspberry/AddNewRobotResponse.h>


namespace laserbot_raspberry
{

struct AddNewRobot
{

typedef AddNewRobotRequest Request;
typedef AddNewRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddNewRobot
} // namespace laserbot_raspberry


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laserbot_raspberry::AddNewRobot > {
  static const char* value()
  {
    return "0cb5143ed23a5de01874507c8711c4d5";
  }

  static const char* value(const ::laserbot_raspberry::AddNewRobot&) { return value(); }
};

template<>
struct DataType< ::laserbot_raspberry::AddNewRobot > {
  static const char* value()
  {
    return "laserbot_raspberry/AddNewRobot";
  }

  static const char* value(const ::laserbot_raspberry::AddNewRobot&) { return value(); }
};


// service_traits::MD5Sum< ::laserbot_raspberry::AddNewRobotRequest> should match 
// service_traits::MD5Sum< ::laserbot_raspberry::AddNewRobot > 
template<>
struct MD5Sum< ::laserbot_raspberry::AddNewRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laserbot_raspberry::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_raspberry::AddNewRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laserbot_raspberry::AddNewRobotRequest> should match 
// service_traits::DataType< ::laserbot_raspberry::AddNewRobot > 
template<>
struct DataType< ::laserbot_raspberry::AddNewRobotRequest>
{
  static const char* value()
  {
    return DataType< ::laserbot_raspberry::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_raspberry::AddNewRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laserbot_raspberry::AddNewRobotResponse> should match 
// service_traits::MD5Sum< ::laserbot_raspberry::AddNewRobot > 
template<>
struct MD5Sum< ::laserbot_raspberry::AddNewRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laserbot_raspberry::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_raspberry::AddNewRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laserbot_raspberry::AddNewRobotResponse> should match 
// service_traits::DataType< ::laserbot_raspberry::AddNewRobot > 
template<>
struct DataType< ::laserbot_raspberry::AddNewRobotResponse>
{
  static const char* value()
  {
    return DataType< ::laserbot_raspberry::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_raspberry::AddNewRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASERBOT_RASPBERRY_MESSAGE_ADDNEWROBOT_H
