// Generated by gencpp from file laserbot_server/AddNewRobot.msg
// DO NOT EDIT!


#ifndef LASERBOT_SERVER_MESSAGE_ADDNEWROBOT_H
#define LASERBOT_SERVER_MESSAGE_ADDNEWROBOT_H

#include <ros/service_traits.h>


#include <laserbot_server/AddNewRobotRequest.h>
#include <laserbot_server/AddNewRobotResponse.h>


namespace laserbot_server
{

struct AddNewRobot
{

typedef AddNewRobotRequest Request;
typedef AddNewRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddNewRobot
} // namespace laserbot_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laserbot_server::AddNewRobot > {
  static const char* value()
  {
    return "0cb5143ed23a5de01874507c8711c4d5";
  }

  static const char* value(const ::laserbot_server::AddNewRobot&) { return value(); }
};

template<>
struct DataType< ::laserbot_server::AddNewRobot > {
  static const char* value()
  {
    return "laserbot_server/AddNewRobot";
  }

  static const char* value(const ::laserbot_server::AddNewRobot&) { return value(); }
};


// service_traits::MD5Sum< ::laserbot_server::AddNewRobotRequest> should match 
// service_traits::MD5Sum< ::laserbot_server::AddNewRobot > 
template<>
struct MD5Sum< ::laserbot_server::AddNewRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laserbot_server::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_server::AddNewRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laserbot_server::AddNewRobotRequest> should match 
// service_traits::DataType< ::laserbot_server::AddNewRobot > 
template<>
struct DataType< ::laserbot_server::AddNewRobotRequest>
{
  static const char* value()
  {
    return DataType< ::laserbot_server::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_server::AddNewRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laserbot_server::AddNewRobotResponse> should match 
// service_traits::MD5Sum< ::laserbot_server::AddNewRobot > 
template<>
struct MD5Sum< ::laserbot_server::AddNewRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laserbot_server::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_server::AddNewRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laserbot_server::AddNewRobotResponse> should match 
// service_traits::DataType< ::laserbot_server::AddNewRobot > 
template<>
struct DataType< ::laserbot_server::AddNewRobotResponse>
{
  static const char* value()
  {
    return DataType< ::laserbot_server::AddNewRobot >::value();
  }
  static const char* value(const ::laserbot_server::AddNewRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASERBOT_SERVER_MESSAGE_ADDNEWROBOT_H
